fc_nelson_aalen:
  files:
    input:  # name of the input CSV/TSV/sas7bdat file
    output:
      cum_hazard_function: # name of the CSV file containing the survival function data
      hazard_plot:  # name of the PNG image showing the survival plot (Kaplan-Meier plot)
      logrank_test: # If a category column is given: name of CSV file containing the pairwise logrank-test results

  # parameters
  parameters:
    duration_col:  # name of the column containing the time values
    event_col:  # name of the column containing the event values (1=event occurred, 0=censored)
    category_col:  # name of the column containing the categories that shall be analysed separately (e.g. treatment A vs. treatment B)

    # coordinator only:
    differential_privacy:  # amount of differential privacy added to the computation (none, low, middle or high). Only the coordinator's decision is applied.
    multipletesting_method:  # Method used for testing and adjustment of pvalues in the pairwise logrank test
      #bonferroni : one-step correction
      #sidak : one-step correction
      #holm-sidak : step down method using Sidak adjustments
      #holm : step-down method using Bonferroni adjustments
      #simes-hochberg : step-up method (independent)
      #hommel : closed method based on Simes tests (non-negative)
      #fdr_bh : Benjamini/Hochberg (non-negative)
      #fdr_by : Benjamini/Yekutieli (negative)
      #fdr_tsbh : two stage fdr correction (non-negative)
      #fdr_tsbky : two stage fdr correction (non-negative)